# Generated by Django 2.2 on 2022-06-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default='', upload_to='profile_pix'),
            preserve_default=False,
        ),
    ]
